// <auto-generated />
using System;
using FlightSearch.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightSearch.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705200620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightSearch.API.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Turkish Airlines"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pegasus Airlines"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SunExpress"
                        });
                });

            modelBuilder.Entity("FlightSearch.API.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Istanbul",
                            Code = "IST",
                            Name = "Istanbul Airport"
                        },
                        new
                        {
                            Id = 2,
                            City = "Istanbul",
                            Code = "SAW",
                            Name = "Sabiha Gokcen Airport"
                        },
                        new
                        {
                            Id = 3,
                            City = "Ankara",
                            Code = "ESB",
                            Name = "Esenboga Airport"
                        },
                        new
                        {
                            Id = 4,
                            City = "Izmir",
                            Code = "ADB",
                            Name = "Adnan Menderes Airport"
                        },
                        new
                        {
                            Id = 5,
                            City = "Antalya",
                            Code = "AYT",
                            Name = "Antalya Airport"
                        });
                });

            modelBuilder.Entity("FlightSearch.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightSearch.API.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 1,
                            ArrivalAirportId = 3,
                            DepartureAirportId = 1,
                            DepartureTime = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 2,
                            ArrivalAirportId = 4,
                            DepartureAirportId = 2,
                            DepartureTime = new DateTime(2026, 8, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Price = 1200m
                        },
                        new
                        {
                            Id = 3,
                            AirlineId = 1,
                            ArrivalAirportId = 1,
                            DepartureAirportId = 3,
                            DepartureTime = new DateTime(2026, 8, 3, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Price = 1600m
                        },
                        new
                        {
                            Id = 4,
                            AirlineId = 3,
                            ArrivalAirportId = 5,
                            DepartureAirportId = 4,
                            DepartureTime = new DateTime(2026, 8, 1, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Price = 900m
                        },
                        new
                        {
                            Id = 5,
                            AirlineId = 2,
                            ArrivalAirportId = 2,
                            DepartureAirportId = 5,
                            DepartureTime = new DateTime(2026, 8, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1100m
                        });
                });

            modelBuilder.Entity("FlightSearch.API.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FlightSearch.API.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("FlightSearch.API.Models.Booking", b =>
                {
                    b.HasOne("FlightSearch.API.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightSearch.API.Models.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightSearch.API.Models.TicketType", "TicketType")
                        .WithMany("Bookings")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("FlightSearch.API.Models.Flight", b =>
                {
                    b.HasOne("FlightSearch.API.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightSearch.API.Models.Airport", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightSearch.API.Models.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("FlightSearch.API.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightSearch.API.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FlightSearch.API.Models.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("FlightSearch.API.Models.TicketType", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
